apiVersion: v2
name: echo-server
description:  echo-server for kilchhofer-home
type: application

version: 1.0.0

dependencies:
- name: oauth2-proxy
  version: "10.7.0"
  repository: oci://ghcr.io/oauth2-proxy/charts
