#######################################################
oauth2-proxy:
  resources:
    limits:
      cpu: 200m
      memory: 64Mi
    requests:
      cpu: 1m
      memory: 16Mi

  config:
    existingSecret: echo-server-oauth2-proxy-custom
    configFile: |-
      reverse_proxy = true
      trusted_proxy_ips = [ "10.42.0.0/24" ]
      real_client_ip_header = "X-Forwarded-For"
      provider = "oidc"
      provider_display_name = "Pocket ID"
      redirect_url = "http://echo-server-oauth2-proxy.tools.kilchhofer.info/oauth2/callback"
      oidc_issuer_url = "https://auth.kilchhofer.info"
      email_domains = [ "*" ]
      upstreams = [ "http://httpbin.base-infra.svc:8000" ]
      silence_ping_logging = true
      cookie_secure = false
      pass_access_token = true
      pass_authorization_header = true
      allowed_groups = [
          "infrastructure_admins"
      ]
      htpasswd_user_groups = [
          "infrastructure_admins",
          "basic-auth"
      ]
      # display_htpasswd_form = false
      footer = "-"
      banner = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua."

  htpasswdFile:
    enabled: true
    existingSecret: echo-server-oauth2-proxy-htpasswd-file-custom
  ingress:
    enabled: false # We use HTTPRoute instead (see templates/oauth2-proxy-extra/httproute.yaml)
