{
 "title": "Cert Manager Overview",
 "tags": [
  "cert-manager",
  "infra"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "label_values(certmanager_certificate_ready_status{ }, cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Certificates Ready",
   "type": "stat",
   "description": "The number of certificates in the ready state.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (condition,cluster) (certmanager_certificate_ready_status{cluster=\"$cluster\"})",
     "legendFormat": "{{condition }}"
    }
   ]
  },
  {
   "title": "Soonest Cert Expiry",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(certmanager_certificate_expiration_timestamp_seconds{cluster=\"$cluster\" } > 0) - time()"
    }
   ]
  },
  {
   "title": "Certificates",
   "type": "table",
   "description": "Status of the certificates. Values are True, False or Unknown.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "label_join(avg by (name, namespace, condition, exported_namespace,cluster) (certmanager_certificate_ready_status{ cluster=\"$cluster\"} == 1), \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    },
    {
     "expr": "label_join(avg by (name, namespace, exported_namespace) (certmanager_certificate_expiration_timestamp_seconds{cluster=\"$cluster\" }) * 1000, \"namespaced_name\", \"-\", \"namespace\", \"exported_namespace\", \"name\")"
    }
   ]
  },
  {
   "title": "Controller Sync Requests/sec",
   "type": "timeseries",
   "description": "The rate of controller sync requests.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (controller,cluster) (\n  rate(certmanager_controller_sync_call_count{cluster=\"$cluster\" }[$__rate_interval ])\n)",
     "legendFormat": "{{controller }}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "description": "CPU Usage and limits, as percent of a vCPU core. ",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (pod,cluster) (rate(container_cpu_usage_seconds_total{namespace=\"cert-manager\" ,cluster=\"$cluster\"}[$__rate_interval ]))",
     "legendFormat": "CPU {{pod }}"
    }
   ]
  },
  {
   "title": "CPU Throttling",
   "type": "timeseries",
   "description": "Percent of the time that the CPU is being throttled. Higher is badderer. ",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg by (container,cluster) (\n  rate(container_cpu_cfs_throttled_periods_total{namespace=\"cert-manager\",cluster=\"$cluster\" }[$__rate_interval ])\n  /\n  rate(container_cpu_cfs_periods_total{namespace=\"cert-manager\",cluster=\"$cluster\" }[$__rate_interval ])\n)",
     "legendFormat": "{{container }}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "timeseries",
   "description": "Memory utilisation and limits.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (container,cluster) (container_memory_usage_bytes{namespace=\"cert-manager\",cluster=\"$cluster\" })",
     "legendFormat": "Memory {{container }}"
    },
    {
     "expr": "avg by (container,cluster) (kube_pod_container_resource_limits_memory_bytes{namespace=\"cert-manager\",cluster=\"$cluster\" })",
     "legendFormat": "Limit {{container  }}"
    },
    {
     "expr": "avg by (container,cluster) (kube_pod_container_resource_requests_memory_bytes{namespace=\"cert-manager\",cluster=\"$cluster\" })",
     "legendFormat": "Request {{pod }}"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "description": "Network ingress/egress.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "avg(\n  sum without (interface,cluster) (\n    rate(container_network_receive_bytes_total{namespace=\"cert-manager\",cluster=\"$cluster\" }[$__rate_interval ])\n  )\n)",
     "legendFormat": "receive"
    },
    {
     "expr": "avg(\n  sum without (interface,cluster) (\n    rate(container_network_transmit_bytes_total{namespace=\"cert-manager\",cluster=\"$cluster\" }[$__rate_interval ])\n  )\n)",
     "legendFormat": "transmit"
    }
   ]
  }
 ]
}