{
 "title": "Kyverno Policy Reporting",
 "description": "Detailed Reports about Kyverno policies",
 "tags": [ "Kyverno" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(vm_app_version{job=\"vmagent\"}, cluster)"
    }
   },
   {
    "name": "policy",
    "label": "Policy",
    "query": {
     "query": "label_values(policy_report_result{cluster=~\"$cluster\"}, policy)"
    }
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values(policy_report_result{cluster=~\"$cluster\"}, category)"
    }
   },
   {
    "name": "severity",
    "label": "Severity",
    "query": {
     "query": "label_values(policy_report_result{cluster=~\"$cluster\"}, severity)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(policy_report_result{cluster=~\"$cluster\"}, namespace)"
    }
   },
   {
    "name": "kind",
    "label": "Kind",
    "query": {
     "query": "label_values(policy_report_result{cluster=~\"$cluster\"}, kind)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Failing Policies by Namespace",
   "type": "bargauge",
   "gridPos": { "h": 12, "w": 20, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=~\"fail\", cluster=~\"$cluster\"} > 0) by (namespace)",
     "legendFormat": "{{ namespace }}"
    }
   ]
  },
  {
   "title": "ClusterPolicy Error Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"error\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Policy Error Status",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"error\", cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Failing Policies|ClusterPolicies Graph",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{status=~\"fail|error\", cluster=~\"$cluster\"} > 0) by (policy)",
     "legendFormat": "{{ policy }}"
    },
    {
     "expr": "sum(policy_report_result{status=~\"fail|error\", cluster=~\"$cluster\"} > 0) by (policy)",
     "legendFormat": "{{ policy }}"
    }
   ]
  },
  {
   "title": "Status Timeline",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\",status=\"fail\", cluster=~\"$cluster\"} > 0) by (status, namespace)",
     "legendFormat": "{{ namespace }} {{ status }}"
    }
   ]
  },
  {
   "title": "Failed Resources (namespaced)",
   "type": "table",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sum(policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", namespace=~\"$namespace\", status=~\"fail\", cluster=~\"$cluster\"}) by (cluster, namespace,category,policy,rule,kind,name,severity,status)"
    }
   ]
  },
  {
   "title": "Failed Resources (cluster-scoped)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
   "targets": [
    {
     "expr": "sum(cluster_policy_report_result{policy=~\"$policy\", category=~\"$category\", severity=~\"$severity\", kind=~\"$kind\", status=\"fail\", cluster=~\"$cluster\"}) by (cluster, policy,rule,kind,name,status,severity,category)"
    }
   ]
  }
 ]
}