apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: echo-server-oauth2-proxy-custom
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-k3s-secrets

  target:
    name: echo-server-oauth2-proxy-custom

  dataFrom:
  - extract:
      key: /k3s/echo-server/oauth2-proxy
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: echo-server-oauth2-proxy-htpasswd-file-custom
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-k3s-secrets

  target:
    name: echo-server-oauth2-proxy-htpasswd-file-custom

  data:
    - secretKey: users.txt
      remoteRef:
        key: /k3s/echo-server/htpasswdFile-entries
