apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-webhook
  namespace: {{ .Release.Namespace }}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-k3s-secrets

  target:
    name: github-webhook

  data:
    - secretKey: secret
      remoteRef:
        key: /k3s/github-exporter/webhook
