{
 "title": "Controller-Runtime-Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total,cluster)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{cluster=\"$cluster\"},namespace)"
    }
   },
   {
    "name": "job",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", cluster=\"$cluster\"},job)"
    }
   },
   {
    "name": "pod",
    "label": "pod",
    "query": {
     "query": "label_values(controller_runtime_reconcile_total{namespace=~\"$namespace\", job=~\"$job\", cluster=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Reconciliation Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of workers in use",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "controller_runtime_active_workers{job=\"$job\", namespace=\"$namespace\"}",
     "legendFormat": "{{controller}} {{instance}}"
    }
   ]
  },
  {
   "title": "Total Reconciliation Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliations per controller",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, pod)",
     "legendFormat": "{{instance}} {{pod}}"
    }
   ]
  },
  {
   "title": "Reconciliation Error Count Per Controller",
   "type": "timeseries",
   "description": "Total number of reconciliation errors per controller",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "cpm" } },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_errors_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, pod)",
     "legendFormat": "{{instance}} {{pod}}"
    }
   ]
  },
  {
   "title": "Work Queue Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "WorkQueue Depth",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "workqueue_depth{job=\"$job\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Seconds For Items Stay In Queue (before being requested) (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds an item stays in workqueue before being requested",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_queue_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_adds_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}}"
    }
   ]
  },
  {
   "title": "Unfinished Seconds",
   "type": "gauge",
   "description": "How many seconds of work has done that is in progress and hasn't been observed by work_duration.\nLarge values indicate stuck threads.\nOne can deduce the number of stuck threads by observing the rate at which this increases.",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(workqueue_unfinished_work_seconds{job=\"$job\", namespace=\"$namespace\"}[5m])"
    }
   ]
  },
  {
   "title": "Seconds Processing Items From WorkQueue (P50, P90, P99)",
   "type": "timeseries",
   "description": "How long in seconds processing an item from workqueue takes.",
   "gridPos": { "h": 9, "w": 11, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P50 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P90 {{name}} {{instance}} "
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(workqueue_work_duration_seconds_bucket{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name, le))",
     "legendFormat": "P99 {{name}} {{instance}} "
    }
   ]
  },
  {
   "title": "Work Queue Retries Rate",
   "type": "timeseries",
   "description": "Total number of retries handled by workqueue",
   "gridPos": { "h": 9, "w": 10, "x": 14, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(rate(workqueue_retries_total{job=\"$job\", namespace=\"$namespace\"}[5m])) by (instance, name)",
     "legendFormat": "{{name}} {{instance}} "
    }
   ]
  }
 ]
}