apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-token
spec:
  refreshInterval: 6h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: akeyless-k3s-secrets

  target:
    name: cloudflared-token

  data:
    - secretKey: tunnelToken
      remoteRef:
        key: /cloudflare-tunnels/k3s/token
