alloy:
  crds:
    create: false
  configReloader:
    enabled: false
  alloy:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 5m
        memory: 32Mi
    configMap:
      content: |
        loki.write "default" {
          endpoint {
            url = "https://logs-prod-eu-west-0.grafana.net/loki/api/v1/push"

            // Get basic authentication based on environment variables.
            basic_auth {
              username = sys.env("LOKI_USER")
              password = sys.env("LOKI_PASSWORD")
            }
          }
        }

        loki.source.syslog "local" {
          listener {
            address  = "0.0.0.0:5140"
            labels   = { component = "loki.source.syslog", protocol = "tcp" }
          }

          listener {
            address  = "0.0.0.0:5140"
            protocol = "udp"
            labels   = { component = "loki.source.syslog", protocol = "udp" }
          }

          forward_to = [loki.write.local.receiver]
        }
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: true
    extraEnv:
      - name: LOKI_USER
        valueFrom:
          secretKeyRef:
            name: grafana-cloud-creds
            key: user
      - name: LOKI_PASSWORD
        valueFrom:
          secretKeyRef:
            name: grafana-cloud-creds
            key: password
    extraPorts:
      - name: syslog-tcp
        targetPort: 5140
        protocol: TCP
      - name: syslog-udp
        targetPort: 5140
        protocol: UDP

  rbac:
    create: false
  service:
    # Use custom Service (resp. 2 Services) to expose the Syslog server on UDP and TCP
    enabled: false
  controller:
    type: 'deployment'
